# Generated by Django 3.1.1 on 2021-02-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicuser',
            name='instrument',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
