# Generated by Django 3.1.1 on 2021-02-24 02:32

import accounts.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210221_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='bandname',
            field=models.CharField(max_length=100, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='band',
            name='city',
            field=accounts.models.CapitalizedCityField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z_-]+$', "Only alphabetical characters and '-' and '_' are allowed.")]),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=accounts.models.LowerCaseCharField(max_length=100, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='musicuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z_-]+$', "Only alphabetical characters and '-' and '_' are allowed.")], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='musicuser',
            name='instrument',
            field=accounts.models.LowerCaseCharField(blank=True, default=None, max_length=80, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z_-]+$', "Only alphabetical characters and '-' and '_' are allowed.")]),
        ),
        migrations.AlterField(
            model_name='musicuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z_-]+$', "Only alphabetical characters and '-' and '_' are allowed.")], verbose_name='last name'),
        ),
    ]
