# Generated by Django 3.1.1 on 2021-02-28 02:33

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210223_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='band',
            name='city',
            field=accounts.models.CapitalizedCityField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z-_]+$', "Only alphabetical characters and '-' and '_' are allowed.")]),
        ),
        migrations.AlterField(
            model_name='musicuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z-_]+$', "Only alphabetical characters and '-' and '_' are allowed.")], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='musicuser',
            name='instrument',
            field=accounts.models.LowerCaseCharField(blank=True, default=None, max_length=80, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z-_]+$', "Only alphabetical characters and '-' and '_' are allowed.")]),
        ),
        migrations.AlterField(
            model_name='musicuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z-_]+$', "Only alphabetical characters and '-' and '_' are allowed.")], verbose_name='last name'),
        ),
    ]
