# Generated by Django 3.1.1 on 2021-02-28 03:19

import accounts.models
import django.contrib.auth.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210227_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=accounts.models.CapitalizedCityField(max_length=100, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()]),
        ),
    ]
