# Generated by Django 3.1.1 on 2021-03-04 19:16

import accounts.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210227_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicuser',
            name='first_name',
            field=accounts.models.CapitalizedCityField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z-_]+$', "Only alphabetical characters and '-' and '_' are allowed.")], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='musicuser',
            name='last_name',
            field=accounts.models.CapitalizedCityField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z-_]+$', "Only alphabetical characters and '-' and '_' are allowed.")], verbose_name='last name'),
        ),
    ]
